// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Main$ShowPrettyPkg    = require("./main.js");
var Version$ShowPrettyPkg = require("./Version.js");

Version$ShowPrettyPkg.noop(/* () */0);

Main$ShowPrettyPkg.noop(/* () */0);

/*  Not a pure module */
