// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var $$__dirname = ( __dirname );

var rootExecPath = ( process.cwd() );

exports.$$__dirname  = $$__dirname;
exports.rootExecPath = rootExecPath;
/* __dirname Not a pure module */
