// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var $$__dirname = ( __dirname );

var rootExecPath = ( process.cwd() );

var packageJsonPath = rootExecPath + "/package.json";

var newLine = "\n";

var tab = "\t";

exports.$$__dirname     = $$__dirname;
exports.rootExecPath    = rootExecPath;
exports.packageJsonPath = packageJsonPath;
exports.newLine         = newLine;
exports.tab             = tab;
/* __dirname Not a pure module */
