// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List                = require("bs-platform/lib/js/list.js");
var Root$ShowPrettyPkg  = require("./Root.js");
var Utils$ShowPrettyPkg = require("./Utils.js");

function displayScripts() {
  var scriptsJson = Utils$ShowPrettyPkg.getJsonKey("scripts");
  var scripts;
  if (scriptsJson) {
    var match = scriptsJson[0];
    scripts = typeof match === "number" ? /* :: */[
        /* Script */[
          "none",
          "none"
        ],
        /* [] */0
      ] : (
        match.tag === 3 ? List.map((function (item) {
                  var match = item[1];
                  if (typeof match === "number") {
                    return /* Script */[
                            "none",
                            "none"
                          ];
                  } else if (match.tag) {
                    return /* Script */[
                            "none",
                            "none"
                          ];
                  } else {
                    return /* Script */[
                            item[0],
                            match[0]
                          ];
                  }
                }), match[0]) : /* :: */[
            /* Script */[
              "none",
              "none"
            ],
            /* [] */0
          ]
      );
  } else {
    scripts = /* :: */[
      /* Script */[
        "none",
        "none"
      ],
      /* [] */0
    ];
  }
  console.log(Utils$ShowPrettyPkg.formattedHeader("Project Commands"));
  return List.iter((function (item) {
                var name = item[0];
                var exit = 0;
                if (name === "none") {
                  if (item[1] === "none") {
                    return /* () */0;
                  } else {
                    exit = 1;
                  }
                } else {
                  exit = 1;
                }
                if (exit === 1) {
                  console.log(Utils$ShowPrettyPkg.formattedName(name));
                  console.log(Utils$ShowPrettyPkg.formattedCommand(item[1]));
                  return /* () */0;
                }
                
              }), scripts);
}

function noop() {
  return /* () */0;
}

Root$ShowPrettyPkg.displayRoot(/* () */0);

displayScripts(/* () */0);

exports.displayScripts = displayScripts;
exports.noop           = noop;
/*  Not a pure module */
