// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Chalk                   = require("chalk");
var Constants$ShowPrettyPkg = require("./Constants.js");

function displayRoot() {
  console.log(Chalk.bold("Project Root"));
  console.log(Chalk.yellow(Chalk.bold(Constants$ShowPrettyPkg.packageJsonPath)));
  return /* () */0;
}

exports.displayRoot = displayRoot;
/* chalk Not a pure module */
