// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Fs                      = require("fs");
var Json                    = require("rex-json/./src/Json.js");
var Chalk                   = require("chalk");
var Constants$ShowPrettyPkg = require("./Constants.js");

function formattedCommand(cmd) {
  var coloured = Chalk.yellow(cmd);
  return "" + (String(Constants$ShowPrettyPkg.tab) + ("" + (String(Constants$ShowPrettyPkg.tab) + ("" + (String(coloured) + "")))));
}

function formattedName(name) {
  var coloured = Chalk.white(name);
  return "" + (String(Constants$ShowPrettyPkg.tab) + ("- " + (String(coloured) + "")));
}

function formattedHeader(name) {
  var formatted = Chalk.bold(name);
  return "" + (String(Constants$ShowPrettyPkg.newLine) + ("" + (String(formatted) + "")));
}

function formattedVersion(version) {
  var formatted = Chalk.yellow(version);
  return Chalk.bold("Version " + (String(formatted) + ""));
}

function formattedError(error) {
  var formatted = Chalk.red(error);
  return Chalk.bold("Version " + (String(formatted) + ""));
}

function getJsonKey(key) {
  return Json.get(key, Json.parse(Fs.readFileSync(Constants$ShowPrettyPkg.packageJsonPath, "utf8")));
}

exports.formattedCommand = formattedCommand;
exports.formattedName    = formattedName;
exports.formattedHeader  = formattedHeader;
exports.formattedVersion = formattedVersion;
exports.formattedError   = formattedError;
exports.getJsonKey       = getJsonKey;
/* fs Not a pure module */
