// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Fs                      = require("fs");
var Json                    = require("rex-json/./src/Json.js");
var Chalk                   = require("chalk");
var Constants$ShowPrettyPkg = require("./Constants.js");

var version = Json.get("version", Json.parse(Fs.readFileSync(Constants$ShowPrettyPkg.rootExecPath + "/package.json", "utf8")));

if (version) {
  var match = version[0];
  if (typeof match !== "number") {
    if (!match.tag) {
      console.log(Chalk.bold(Chalk.bold("Version") + (" " + Chalk.yellow(match[0]))));
    }
    
  }
  
} else {
  console.log("\t- " + Chalk.white("No Version Found"));
}

exports.version = version;
/* version Not a pure module */
